[package]
name = "imitare"
description = "a fake file generator"
license = "GPL-3.0-or-later"
repository = "https://github.com/mys721tx/imitare"
version = "0.1.0"
authors = ["Yishen Miao <mys721tx@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7"
clap = "2.33"
